### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by TheusFacin** [TheusFacin/dragon-age-sheet#1]
# Coisas para fazer

### Home:
- [x] Criação da página
- [x] Criação da rota
- [x] Buscar os personagens salvos
- [x] Apresentação dos personagens
- [ ] Estilização da página
- [ ] Criação de novo personagem
- [ ] Exportação dos personagens
- [ ] Importação dos personagens

### Ficha:
- [x] Criação da página
- [x] Criação da rota
- [x] Apresentação dos dados do personagem
- [x] Estilização da página
- [ ] Edição dos dados:
  - [x] Habilidades
  - [ ] Armas e feitiços
  - [ ] Dinheiro
  - [ ] Atributos
  - [ ] Informações do personagem
  - [ ] Imagem e nome
- [ ] Salvar

### Personagem:
- [ ] Criação da página
- [ ] Criação da rota
- [ ] Apresentação dos dados
- [ ] Estilização da página
- [ ] Edição dos dados
- [ ] Salvar

### Equipamento
- [ ] Criação da página
- [ ] Criação da rota
- [ ] Apresentação dos dados
- [ ] Estilização da página
- [ ] Edição dos dados
- [ ] Salvar

### Diário
- [ ] Criação da página
- [ ] Criação da rota
- [ ] Apresentação dos dados
- [ ] Estilização da página
- [ ] Edição dos dados
- [ ] Salvar

### TitleBar:
- [x] Estilização
- [x] Funcionalidades:
  - [x] Arrastar a janela
  - [x] Botões (minimizar, maximizar, "desmaximizar", fechar)
  - [x] Título dinâmico
  - [x] Voltar
